# Generated by Django 5.0.2 on 2024-04-19 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(max_length=255, verbose_name='Пол ученика')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.CharField(max_length=255, verbose_name='Оценка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(max_length=255, verbose_name='Уровень физподготовки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.IntegerField(verbose_name='Класс ученика (номер)')),
                ('class_name', models.CharField(max_length=255, verbose_name='Класс ученика (буква)')),
                ('class_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Куратор класса')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название норматива')),
                ('has_numeric_value', models.BooleanField(verbose_name='Если True, то это умение. Иначе - норматив')),
                ('who_added', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил норматив')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField(verbose_name='Значение')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standarts.classes', verbose_name='Класс')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standarts.gender', verbose_name='Пол ученика')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standarts.level', verbose_name='Уровень физподготовки')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standarts.standards', verbose_name='Норматив')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('recruitment_year', models.DateField(verbose_name='Год набора')),
                ('birthday', models.DateField(verbose_name='Дата рождения ученика')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standarts.classes', verbose_name='Класс ученика (номер)')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standarts.gender', verbose_name='Пол ученика')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsStandards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField(verbose_name='Значение')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standarts.classes', verbose_name='Класс')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standarts.grades', verbose_name='Оценка')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standarts.standards', verbose_name='Норматив')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standarts.students', verbose_name='Ученик')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
