# Generated by Django 5.0.2 on 2024-05-23 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='high_level_value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лучшее значение для уровня'),
        ),
        migrations.AlterField(
            model_name='level',
            name='low_level_value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальное значение для уровня'),
        ),
        migrations.AlterField(
            model_name='level',
            name='middle_level_value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Среднее значение для уровня'),
        ),
    ]
