# Generated by Django 5.0.2 on 2024-05-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_alter_level_high_level_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstandard',
            name='grade',
            field=models.IntegerField(max_length=255, verbose_name='Оценка'),
        ),
    ]
