# Generated by Django 5.0.2 on 2024-05-23 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0004_alter_studentstandard_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstandard',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оценка'),
        ),
    ]
