# Generated by Django 5.0.2 on 2024-05-23 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0006_studentstandard_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='standards.standard', verbose_name='Норматив, к которому относится данный уровень'),
        ),
    ]
