# Generated by Django 5.0.2 on 2024-05-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0007_alter_level_standard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='level',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='restored_at',
        ),
        migrations.DeleteModel(
            name='StandardValue',
        ),
    ]
