# Generated by Django 5.0.2 on 2024-05-24 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0008_remove_level_deleted_at_remove_level_restored_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstandard',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='standards.level', verbose_name='Уровень'),
        ),
    ]
